sudo: required

language: bash

addons:
  apt:
    packages:
      - docker-ce
      - grep

env:
  global:
    - IMAGE="capture-website-cli"
    - IMAGE_NAME="quay.io/hermsi1337/${IMAGE}"

before_script:
  - sudo sysctl -w net.ipv4.ip_forward=1
  - if [[ "${TRAVIS_BRANCH}" == "master" ]] && [[ "${TRAVIS_PULL_REQUEST}" == "false" ]]; then docker login -u "${DOCKER_LOGIN_USER}" -p "${DOCKER_LOGIN_PASSWORD}" quay.io ; fi

script:
  - |
    #!/usr/bin/env bash

    set -xe

    NODE_VERSIONS=("15")

    for NODE_VERSION in "${NODE_VERSIONS[@]}"; do
      PATCH_RELEASE_VERSION="$(docker run --rm -e SKIP_UPDATE_CHECK="1" --entrypoint /usr/bin/env -t quay.io/bitnami/node:${NODE_VERSION} /bin/bash -c 'npm install --silent -g capture-website-cli &>/dev/null && npm list -g capture-website-cli | egrep "\@[0-9]+\.[0-9]+\.[0-9]+.*" | cut -d "@" -f 2 | head -n1' | awk '{print $1}' | tail -1 | tr -d "\r")"
      MINOR_RELEASE_VERSION="${PATCH_RELEASE_VERSION%.*}"
      MAJOR_RELEASE_VERSION="${MINOR_RELEASE_VERSION%.*}"

      TAGS=("latest-node${NODE_VERSION}")
      TAGS+=("${PATCH_RELEASE_VERSION}")
      TAGS+=("${PATCH_RELEASE_VERSION}-node${NODE_VERSION}")
      TAGS+=("${MINOR_RELEASE_VERSION}")
      TAGS+=("${MINOR_RELEASE_VERSION}-node${NODE_VERSION}")
      TAGS+=("${MAJOR_RELEASE_VERSION}")
      TAGS+=("${MAJOR_RELEASE_VERSION}-node${NODE_VERSION}")

      docker build -t "${IMAGE_NAME}:latest" --build-arg NODE_VERSION="${NODE_VERSION}" --build-arg CAPTURE_WEBSITE_CLI_VERSION="${PATCH_RELEASE_VERSION}" .

      for TAG in "${TAGS[@]}" ; do
        docker tag "${IMAGE_NAME}:latest" "${IMAGE_NAME}:${TAG}"
      done

      if [[ "${TRAVIS_BRANCH}" == "master" ]] && [[ "${TRAVIS_PULL_REQUEST}" == "false" ]]; then
        for TAG in "${TAGS[@]}" ; do
          docker push "${IMAGE_NAME}:${TAG}"
        done
      fi
    done